apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - service-account.yaml
  - app-a.yaml
  - app-b.yaml
  - pod-monitoring.yaml
  - pdb.yaml
  - network-policy.yaml

